#!/bin/bash
jack_connect "system:capture_1" julia:in
jack_connect "system:capture_1" claas:in
jack_connect "system:capture_1" giso:in
jack_connect "system:capture_2" simon:in
jack_connect julia:out "system:playback_13"
jack_connect claas:out "system:playback_14"
jack_connect giso:out "system:playback_15"
jack_connect simon:out "system:playback_16"

aconnect "Hammerfall DSP":0 mididings:0
