#!/bin/bash

# FCB1010 preset layout:

# Stop-Taste Bank 1
p[15]="default mute"
c[15]="send_osc 3819 /ardour/transport_stop"

# Stop-Taste Bank 2
p[25]="default mute"
c[25]="send_osc 3819 /ardour/transport_stop"

# Bank 3 ist von Reich belegt

# Stop-Taste Bank 4
p[48]="default mute"
c[48]="send_osc 3819 /ardour/transport_stop"

# Bank 5 und 6 snd von Santana belegt

# Stop-Taste Bank 7
p[75]="default mute"
c[75]="send_osc 3819 /ardour/transport_stop"

# Stop-Taste Bank 9
p[95]="default mute"
c[95]="send_osc 3819 /ardour/transport_stop"



# Palestrina: Vestiva i colli
p[91]="default vestiva_intro"
c[91]="send_osc 3819 /ardour/locate 224910000 1;send_osc 3819 /ardour/set_record_enable 1"

# Ansage Claas
p[92]="default"
c[92]="send_osc 3819 /ardour/locate 298044752 1;send_osc 3819 /ardour/set_record_enable 0"

# Lee Santana: Music for Viols
p[70]="default santana_prelude"
c[61]="send_osc 3819 /ardour/locate 153335700 1;send_osc 3819 /ardour/set_record_enable 1"
p[61]="santana_prelude1"
p[62]="santana_prelude2"
p[63]="santana_chaconne_01"
p[64]="santana_chaconne_02"
p[65]="santana_chaconne_03"
p[66]="santana_chaconne_04"
p[67]="santana_chaconne_05"
p[68]="santana_chaconne_06"
p[69]="santana_chaconne_07"
p[51]="santana_chaconne_07b"
p[52]="santana_chaconne_08"
p[53]="santana_chaconne_08a"
p[54]="santana_chaconne_08b"
p[55]="santana_chaconne_08c"
p[56]="santana_chaconne_09"
p[41]="santana_chaconne_11"
p[42]="santana_chaconne_11a"
p[43]="santana_chaconne_11b"
p[44]="santana_chaconne_11c"
p[45]="santana_chaconne_12"
p[46]="santana_chaconne_12a"
p[47]="santana_postlude"

# Ansage Himmlische Koerper
p[49]="default"
c[49]="send_osc 3819 /ardour/locate 308955066 1;send_osc 3819 /ardour/set_record_enable 0"

# Picforth: In Nomine
p[11]="default picforth_init picforth_cycle_test"
c[11]="send_osc 3819 /ardour/locate 185623533 1;send_osc 3819 /ardour/set_record_enable 1"
p[12]="picforth_epicycle_test"
p[13]="picforth_ellipse_test"
p[14]="octave"

# Reich:
p[40]="default reich_init reich_01"
c[40]="send_osc 3819 /ardour/locate 34197376 1;send_osc 3819 /ardour/set_record_enable 1"
p[31]="reich_02"
p[32]="reich_11a"
p[33]="reich_12"
p[34]="reich_19"
p[35]="reich_20"
p[21]="reich_21a"
p[22]="reich_21b"
p[23]="reich_23"

# Ansage Unsterblichkeit
p[26]="default"
c[26]="send_osc 3819 /ardour/locate 305216776 1;send_osc 3819 /ardour/set_record_enable 0"

# Strogers In Nomine:
p[16]="default strogers"
c[16]="send_osc 3819 /ardour/locate 137371500 1;send_osc 3819 /ardour/set_record_enable 1"

# Tye - Rubum:
p[17]="default tye_rubum"
c[17]="send_osc 3819 /ardour/locate 126787500 1;send_osc 3819 /ardour/set_record_enable 1"

# Tye - Trust:
p[18]="default tye_trust"
c[18]="send_osc 3819 /ardour/locate 116203500 1;send_osc 3819 /ardour/set_record_enable 1"

# John Cage: Five
p[71]="default"
c[71]="send_osc 3819 /ardour/locate 2205000 1;send_osc 3819 /ardour/set_record_enable 1"

# Ansage heilige Vaeter;
p[76]="default"
c[76]="send_osc 3819 /ardour/locate 301855766 1;send_osc 3819 /ardour/set_record_enable 0"

# Paert:
p[72]="default paert"
c[72]="send_osc 3819 /ardour/locate 86083200 1;send_osc 3819 /ardour/set_record_enable 1"

# Palestrina: Phaseout. Vestiva
p[73]="default vestiva_phaseout"
#p[73]="default"
c[73]="send_osc 3819 /ardour/locate 19770906 1;send_osc 3819 /ardour/set_record_enable 1"



# controller:
(
    if test -z "${p[$1]}"; then
	echo "[$1 undefined]"
    else
	echo ${p[$1]}
    # upload preset:
	for k in `echo ${p[$1]}`; do
	    cat presets/$k.preset
	    echo ""
	done | hos_sendosc osc.udp://224.1.2.3:6978/
    fi
) &
(
    if test -z "${c[$1]}"; then
	echo "cmd $1 undefined"
    else
	echo ${c[$1]}
	bash -l -c "${c[$1]}"
    fi
) &