#!/bin/bash

# disable screen saver:
xset -dpms
xset s off

# maximum CPU performance:
cpufreq-selector -c 0 -f 3000000
cpufreq-selector -c 1 -f 3000000

# start jackd:
#jackd -P84 -u -p512 -t5000 -c s -dalsa -dhw:DSP -r48000 -p64 -n2 -I33 -O34 &
#jackd -P84 -u -p512 -t5000 -c c -s -S -dalsa -dhw:DSP -r44100 -p64 -n2 -I33 -O34 &
sleep 1

# load Reich delaylines:
hos_delay julia &
hos_delay claas &
hos_delay giso &
hos_delay simon &

# start parameter control/footswitch:
./midi2bash.py &

# check all connections:
./connect

# load default preset:
./loadpreset 15
