#!/bin/bash

# disable screen saver:
xset -dpms
xset s off

# maximum CPU performance:
cpufreq-selector -c 0 -f 3000000
cpufreq-selector -c 1 -f 3000000

# start jackd:
#jackd -P84 -u -p512 -t5000 -c s -dalsa -dhw:DSP -r48000 -p64 -n2 -I33 -O34 &
#jackd -P84 -u -p512 -t5000 -c c -s -S -dalsa -dhw:DSP -r44100 -p64 -n2 -I33 -O34 &
#sleep 1

calfjackhost --load calf-phono.xml &

hos_scope &

sleep 1

hos_cyclephase &

sleep 1

# start parameter control/footswitch:
./midi2bash.py &

# check all connections:
./connect

# load default preset:
./loadpreset 40

./start_mha &