#!/bin/bash
NAME=speiche
NAME=picforth5
../../../build/hos_sampler reich.soundfont reich_v1.pitch reich_v1&
../../../build/hos_sampler reich.soundfont reich_v2.pitch reich_v2&
../../../build/hos_sampler reich.soundfont reich_v3.pitch reich_v3&
sleep 6
jack_connect reich_v1:out system:playback_18
jack_connect reich_v2:out system:playback_19
jack_connect reich_v3:out system:playback_20
sleep 6
send_osc osc.udp://224.1.2.3:6978/ /*/t0 -10
